---
k3s_become: true
k3s_etcd_datastore: true
k3s_install_hard_links: true
k3s_registration_address: "192.168.86.251"
# renovate: datasource=github-releases depName=k3s-io/k3s
k3s_release_version: v1.31.1+k3s1
k3s_server_manifests_templates:
  - custom-cilium-helmchart.yaml
  - kube-vip-ds.yaml
  - kube-vip-rbac.yaml
k3s_use_unsupported_config: true
